# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-29 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20160530_0049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-publication_date']},
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default=False, upload_to=''),
        ),
    ]
